### ISSUE TITLE
chase down continued HPC file system issues (on delete)

### ISSUE THREAD

**Issue by philipmac** [niaid/image_portal_workflows#176]
eg 
https://prefect1.hedwig-workflow-api.niaidprod.net/default/flow-run/795c2568-f673-4e8b-bdb8-1e42ae003e8d

Task 'cleanup_workdir[8]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/gs1/home/macmenaminpe/code/hedwig/prod/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/gs1/home/macmenaminpe/code/hedwig/prod/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/gs1/home/macmenaminpe/code/hedwig/prod/image_portal_workflows/em_workflows/utils/utils.py", line 116, in cleanup_workdir
    fp.rm_workdir()
  File "/gs1/home/macmenaminpe/code/hedwig/prod/image_portal_workflows/em_workflows/file_path.py", line 241, in rm_workdir
    shutil.rmtree(self.working_dir)
  File "/gs1/home/macmenaminpe/miniconda3/lib/python3.9/shutil.py", line 717, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/gs1/home/macmenaminpe/miniconda3/lib/python3.9/shutil.py", line 715, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/gs1/Scratch/macmenaminpe_scratch/tmpzrhn8sp5'

**Comment by philipmac** [comment]
Appears to have stopped occurring - closing for now.
