### ISSUE TITLE
Prefect 2 testing -Multichannel run failed in DEV after sucessfuly submission of the pipeline

### ISSUE THREAD

**Issue by NetaFG** [niaid/image_portal_workflows#408]
1) Pipeline run: https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/c1a293a8-cb16-4b48-abee-376574d71efa
2) Hedwig UI: https://goat.niaid.nih.gov:7333/sessions/U2Vzc2lvbjozNTcy/samples
3) File system: \\ai-fas12.niaid.nih.gov\RMLSOHedwigDev\Projects\RTB\darrellh\valekseyev-2023-1012-11\Protein-2023-1018-HQ_Thumbnails-Thumbnails
![image](https://github.com/niaid/image_portal_workflows/assets/78621685/f77aebc8-73e4-4530-9f25-57f776c61a1c)

**Comment by philipmac** [comment]
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/prefect/engine.py", line 844, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 293, in aresult
    return await asyncio.wrap_future(self.future)
  File "/gs1/home/hedwig_dev/dev/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 355, in _run_async
    result = await coro
  File "/gs1/home/hedwig_dev/image_portal_workflows/em_workflows/czi/flow.py", line 244, in czi_flow
    *[generate_czi_imageset(file_path=fp) for fp in fps]
TypeError: 'PrefectFuture' object is not iterable
```

soln:
wait on future to return result before async call.
eg
`result = future.result()
`

Above failed job re-run here:

https://prefect2.hedwig-workflow-api.niaiddev.net/flow-runs/flow-run/dec5ba2f-fee3-4e0c-bfba-d1efec80bfe6
